theme = "hugo-academic"
baseURL = "/"
languageCode = "en-us"
title = "Chunming Gu's Site"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  name = "Chunming Gu"
  role = "Ph.D. Student"
  organization = "Johns Hopkins University School of Medicine"
  